### ISSUE TITLE
React Streamfield

### ISSUE THREAD

**Issue by zerolab** [davidcondenl/wagtailuiplus#1]
More of a question than anything. Are you aware of https://github.com/wagtail/wagtail/pull/4942?
The style changes will make it in core sooner via https://github.com/wagtail/wagtail/pull/5476, but you can already use it via https://github.com/wagtail/wagtail-react-streamfield

**Comment by davidcondenl** [comment]
@zerolab I wasn't, thanks for filling me in. Wagtail React Streamfield looks great, so I'm guessing the stream field related enhancements of my app will become obsolete as soon as Wagtail React Streamfield is out of beta.

However, my intention with this app is to implement various ui related enchancement to the wagtail editor. I have to admit I haven't done a thorough research of the Wagtail roadmap, so please excuse me if I'm coming up with stuff that's already planned. Thanks again for informing me of this.

**Comment by zerolab** [comment]
Not an issue at all. Just stumbled upon your package and I thought I'd check.
We could do better on the roadmap/package ecosystem side of things in the Wagtail world.

No harm having your own package that tweaks things that suit you!

**Comment by davidcondenl** [comment]
Great. Thanks for your interest. Happy to be a part of the Wagtail world :)
